FROM php:8.4-fpm

# Install poppler-utils for pdf2ppm
RUN apt-get update && apt-get install -y poppler-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# COPY backend/ /var/www/html/